sudo: false
language: node_js
node_js:
  - '6'
  - '7'
install:
  - npm i npminstall && npminstall
script:
  - echo "success"
after_script:
  - npminstall codecov && codecov
  - scripts/doc_travis.sh
env:
  global:
  - ENCRYPTION_LABEL: a62186272189
